language: go

go:
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - master

install:
  - go mod tidy
  - go build

script:
  - go mod tidy
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)